-- Generated by scripts/create-test-files.mjs
CREATE TABLE IF NOT EXISTS files (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  filename TEXT NOT NULL UNIQUE,
  content TEXT NOT NULL DEFAULT '',
  is_external INTEGER NOT NULL DEFAULT 0,
  external_url TEXT,
  created_by TEXT NOT NULL DEFAULT 'SYSTEM',
  updated_by TEXT NOT NULL DEFAULT 'SYSTEM',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

INSERT INTO files (filename, content, is_external, external_url, created_by, updated_by)
VALUES ('all-characters-test.txt', 'ARS-40 Character Coverage Test

Uppercase:
ABCDEFGHIJKLMNOPQRSTUVWXYZ

Lowercase:
abcdefghijklmnopqrstuvwxyz

Digits:
0123456789

Whitespace demo (spaces, tab, and blank lines):
A B C
A	B	C

Punctuation & symbols:
! " # $ % & '' ( ) * + , - . /
: ; < = > ? @
[ \ ] ^ _ `
{ | } ~

Extended keyboard mix:
`~1!2@3#4$5%6^7&8*9(0)-_=+
[{]}\|;:''",<.>/?

Unicode sanity check:
é ñ ü ç Ω λ 中 文 ✅

End of test file.
', 0, NULL, 'SYSTEM', 'SYSTEM')
ON CONFLICT(filename) DO UPDATE SET
  content=excluded.content,
  is_external=excluded.is_external,
  external_url=excluded.external_url,
  updated_by='SYSTEM',
  updated_at=datetime('now');
